/**
 * *************************************************
 * Copyright (c) 2019, Grindrod Bank Limited
 * License MIT: https://opensource.org/licenses/MIT
 * **************************************************
 */
/*
 * A3S
 *
 * API Definition for A3S. This service allows authentication, authorisation and accounting.
 *
 * The version of the OpenAPI document: 1.1.0
 * 
 * Generated by: https://openapi-generator.tech
 */

using System;
using System.Linq;
using System.Text;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.Runtime.Serialization;
using Newtonsoft.Json;
using za.co.grindrodbank.a3s.Converters;

namespace za.co.grindrodbank.a3s.Models
{ 
    /// <summary>
    /// Model a consent of service that needs to be agreed to by a user. 
    /// </summary>
    [DataContract]
    public partial class ConsentOfService : IEquatable<ConsentOfService>
    { 
        /// <summary>
        /// Gets or Sets ConsentFileData
        /// </summary>
        [DataMember(Name="consentFileData", EmitDefaultValue=false)]
        public string ConsentFileData { get; set; }

        /// <summary>
        /// Returns the string presentation of the object
        /// </summary>
        /// <returns>String presentation of the object</returns>
        public override string ToString()
        {
            var sb = new StringBuilder();
            sb.Append("class ConsentOfService {\n");
            sb.Append("  ConsentFileData: ").Append(ConsentFileData).Append("\n");
            sb.Append("}\n");
            return sb.ToString();
        }

        /// <summary>
        /// Returns the JSON string presentation of the object
        /// </summary>
        /// <returns>JSON string presentation of the object</returns>
        public string ToJson()
        {
            return JsonConvert.SerializeObject(this, Formatting.Indented);
        }

        /// <summary>
        /// Returns true if objects are equal
        /// </summary>
        /// <param name="obj">Object to be compared</param>
        /// <returns>Boolean</returns>
        public override bool Equals(object obj)
        {
            if (obj is null) return false;
            if (ReferenceEquals(this, obj)) return true;
            return obj.GetType() == GetType() && Equals((ConsentOfService)obj);
        }

        /// <summary>
        /// Returns true if ConsentOfService instances are equal
        /// </summary>
        /// <param name="other">Instance of ConsentOfService to be compared</param>
        /// <returns>Boolean</returns>
        public bool Equals(ConsentOfService other)
        {
            if (other is null) return false;
            if (ReferenceEquals(this, other)) return true;

            return 
                (
                    ConsentFileData == other.ConsentFileData ||
                    ConsentFileData != null &&
                    ConsentFileData.Equals(other.ConsentFileData)
                );
        }

        /// <summary>
        /// Gets the hash code
        /// </summary>
        /// <returns>Hash code</returns>
        public override int GetHashCode()
        {
            unchecked // Overflow is fine, just wrap
            {
                var hashCode = 41;
                // Suitable nullity checks etc, of course :)
                    if (ConsentFileData != null)
                    hashCode = hashCode * 59 + ConsentFileData.GetHashCode();
                return hashCode;
            }
        }

        #region Operators
        #pragma warning disable 1591

        public static bool operator ==(ConsentOfService left, ConsentOfService right)
        {
            return Equals(left, right);
        }

        public static bool operator !=(ConsentOfService left, ConsentOfService right)
        {
            return !Equals(left, right);
        }

        #pragma warning restore 1591
        #endregion Operators
    }
}
